import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderLayout from "@/components/ProviderLayout";
import CartLayout from "@/components/CartLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-6 md:px-20 xl:px-30`}
      >
        <ProviderLayout>
          <CartLayout>
            {children}
          </CartLayout>
        </ProviderLayout>
      </body>
    </html>
  );
}
